\ Bold character set, font designed by J.J. Hoekstra
\ Big bold characters 8 x 14 IBM-font like (code space: ~1800)
\ From well known words: BOUNDS

hex
: ||    ( bitrow -- )
    0  0D parse  10 min bounds
    do  2*  i c@ ch X =  -  loop
    b-b  swap c,  c, ;

create BIGBOLD      \ Big characters 8 x 14 pixels
|| ................    \ BL
|| ................
|| ................
|| ................
|| ................
|| ................
|| ................
|| ................

|| ................    \ !
|| ................
|| ................
|| ..XX.XXXXXXXXXXX
|| ..XX.XXXXXXXXXXX
|| ................
|| ................
|| ................

|| ................    \ "
|| ................
|| ...........XX.XX
|| ............XXXX
|| ................
|| ...........XX.XX
|| ............XXXX
|| ................

|| ................    \ #
|| .....XX..XX.....
|| ...XXXXXXXXXX...
|| .....XX..XX.....
|| .....XX..XX.....
|| ...XXXXXXXXXX...
|| .....XX..XX.....
|| ................

|| ....XX..........    \ $
|| ...XX....XXXX...
|| ...XX...XX..XX..
|| .XXXXXXXXXXXXXXX
|| .XXXXXXXXXXXXXXX
|| ...XX..XX...XX..
|| ...XX..XX..XX...
|| ....XXXX........

|| ................    \ %
|| ...XXX.......XXX
|| .....XXX.....X.X
|| .......XXX....XX
|| ...XX....XXX....
|| ...X.X.....XXX..
|| ...XXX.......XXX
|| ................

|| ....XXXX...XXX..    \ &
|| ...XX...XXXXXXX.
|| ...XX...XXX...XX
|| ...XX..XXXX...XX
|| ....XXXX..XX.XX.
|| .....XXXX..XXX..
|| ....XX..XX......
|| ...X............

|| ................    \ '
|| ................
|| ................
|| ...........XX.XX
|| ............XXXX
|| ................
|| ................
|| ................

|| ................    \ (
|| .......XXXX.....
|| .....XXXXXXXX...
|| ...XXX......XXX.
|| ..XXX........XXX
|| ..X............X
|| ................
|| ................

|| ................    \ )
|| ................
|| ..X............X
|| ..XXX........XXX
|| ...XXX......XXX.
|| .....XXXXXXXX...
|| .......XXXX.....
|| ................

|| ................    \ *
|| .........XX..XX.
|| ..........XXXX..
|| ........XXXXXXXX
|| ..........XXXX..
|| .........XX..XX.
|| ................
|| ................

|| ................    \ +
|| .......XX.......
|| .......XX.......
|| ...XXXXXXXXXX...
|| ...XXXXXXXXXX...
|| .......XX.......
|| .......XX.......
|| ................

|| ................    \ ,
|| ................
|| ................
|| XX.XX...........
|| .XXXX...........
|| ................
|| ................
|| ................

|| ................    \ -
|| .......XX.......
|| .......XX.......
|| .......XX.......
|| .......XX.......
|| .......XX.......
|| .......XX.......
|| ................

|| ................    \ .
|| ................
|| ................
|| ...XX...........
|| ...XX...........
|| ................
|| ................
|| ................

|| ................    \ /
|| ...XXX..........
|| ....XXXX........
|| ......XXXX......
|| ........XXXX....
|| ..........XXXX..
|| ............XXXX
|| ................

|| .....XXXXXXXXX..    \ 0
|| ....XXXXXXXXXXX.
|| ...XXXX......XXX
|| ...XX..XXX....XX
|| ...XX....XXX..XX
|| ...XXX......XXXX
|| ....XXXXXXXXXXX.
|| .....XXXXXXXXX..

|| ................    \ 1
|| ...XX.......XX..
|| ...XX.......XXX.
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ...XX...........
|| ...XX...........
|| ................

|| ...XXX......XX..    \ 2
|| ...XXXX......XX.
|| ...XX.XX......XX
|| ...XX..XX.....XX
|| ...XX...XX....XX
|| ...XX....XX...XX
|| ...XX.....XXXXX.
|| ...XX......XXX..

|| .....XX.........    \ 3
|| ....XX........XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XXX..XX
|| ...XX....XXXX.XX
|| ....XXXXXX..XXXX
|| ......XXX.....XX

|| ......XXXX......    \ 4
|| ......XX.XXX....
|| ......XX...XXX..
|| ......XX.....XXX
|| ......XX........
|| ...XXXXXXXXXXXX.
|| ...XXXXXXXXXXXX.
|| ......XX........

|| ....XX...XXXXXXX    \ 5
|| ...XX....XXXXXXX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ....XXXXXX....XX
|| .....XXXX.......

|| ......XXXXXXX...    \ 6
|| ....XXXXXXXXXXX.
|| ...XXX...XX...XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XXX..XXX...XX
|| ....XXXXXX...XX.
|| .....XXXX.......

|| ..............XX    \ 7
|| ...XX.........XX
|| ...XXX..XX....XX
|| .....XXXXX....XX
|| .......XXX....XX
|| ........XXXX..XX
|| ........XX.XXXXX
|| .............XXX

|| .....XXXX.......    \ 8
|| ....XXXXXX.XXXX.
|| ...XX....XXX.XXX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XXX.XXX
|| ....XXXXXX.XXXX.
|| .....XXXX.......

|| ....XX....XXXX..    \ 9
|| ....XX..XXXXXXXX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XXX...XX...XX
|| ....XXXXXXXXXXX.
|| ......XXXXXXX...

|| ................    \ :
|| ................
|| ................
|| ...XX.....XX....
|| ...XX.....XX....
|| ................
|| ................
|| ................

|| ................    \ ;
|| ................
|| ................
|| XX.XX.....XX....
|| .XXXX.....XX....
|| ................
|| ................
|| ................

|| ................    \ <
|| ................
|| .......XX.......
|| ......XXXX......
|| .....XX..XX.....
|| ....XX....XX....
|| ...XX......XX...
|| ................

|| ................    \ =
|| .....XX..XX.....
|| .....XX..XX.....
|| .....XX..XX.....
|| .....XX..XX.....
|| .....XX..XX.....
|| .....XX..XX.....
|| ................

|| ................    \ >
|| ...XX......XX...
|| ....XX....XX....
|| .....XX..XX.....
|| ......XXXX......
|| .......XX.......
|| ................
|| ................

|| ............XX..    \ ?
|| .............XX.
|| ..............XX
|| ...XX.XXX.....XX
|| ...XX.XXX.....XX
|| ........XX....XX
|| .........XXXXXX.
|| ..........XXXX..

|| .....XXXXXXX....    \ @
|| ....XXXXXXXXX...
|| ...XXX......XX..
|| ...XX..XXX..XX..
|| ...XX.X...X.XX..
|| ...XX.XXXX..XX..
|| ...XX..XXX.XX...
|| ........XXXX....

|| ...XXXXXXXXXX...    \ A
|| ...XXXXXXXXXXXX.
|| .......XX....XXX
|| .......XX.....XX
|| .......XX.....XX
|| .......XX....XX.
|| ...XXXXXXXXXXXX.
|| ...XXXXXXXXXX...

|| ...XXXXXXXXXXXXX    \ B
|| ...XXXXXXXXXXXXX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XXX.XX.
|| ....XXXXXX.XXX..
|| .....XXXX.......

|| ......XXXXXXX...    \ C
|| ....XXXXXXXXXXX.
|| ...XXX.......XXX
|| ...XX.........XX
|| ...XX.........XX
|| ...XX.........XX
|| ....XX.......XX.
|| .....XX.....XX..

|| ...XXXXXXXXXXXXX    \ D
|| ...XXXXXXXXXXXXX
|| ...XX.........XX
|| ...XX.........XX
|| ...XX.........XX
|| ...XX.........XX
|| ....XXXXXXXXXXX.
|| .....XXXXXXXXX..

|| ...XXXXXXXXXXXXX    \ E
|| ...XXXXXXXXXXXXX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XX.........XX

|| ...XXXXXXXXXXXXX    \ F
|| ...XXXXXXXXXXXXX
|| ........XX....XX
|| ........XX....XX
|| ........XX....XX
|| ........XX....XX
|| ........XX....XX
|| ..............XX

|| .....XXXXXXXXX..    \ G
|| ....XXXXXXXXXXX.
|| ...XXX.......XXX
|| ...XX.........XX
|| ...XX...XX....XX
|| ...XX...XX....XX
|| ...XXXXXXX....XX
|| ....XXXXXX...XX.

|| ...XXXXXXXXXXXXX    \ H
|| ...XXXXXXXXXXXXX
|| ........XX......
|| ........XX......
|| ........XX......
|| ........XX......
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX

|| ................    \ I
|| ...XX.........XX
|| ...XX.........XX
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ...XX.........XX
|| ...XX.........XX
|| ................

|| ....XX..........    \ J
|| ....XX........XX
|| ...XX.........XX
|| ...XX.........XX
|| ...XX.........XX
|| ...XXX........XX
|| ....XXXXXXXXXXXX
|| ......XXXXXXXXXX

|| ...XXXXXXXXXXXXX    \ K
|| ...XXXXXXXXXXXXX
|| .......XXXX.....
|| ......XXXXXX....
|| .....XXX...XX...
|| ....XXX.....XX..
|| ...XXX.......XX.
|| ...XX.........XX

|| ................    \ L
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ...XX...........
|| ...XX...........
|| ...XX...........
|| ...XX...........
|| ...XX...........

|| ...XXXXXXXXXXXXX    \ M
|| ...XXXXXXXXXXXXX
|| ...........XXX..
|| .........XXX....
|| .........XXX....
|| ...........XXX..
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX

|| ...XXXXXXXXXXXXX    \ N
|| ...XXXXXXXXXXXXX
|| ...........XXX..
|| .........XXX....
|| .......XXX......
|| .....XXX........
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX

|| .....XXXXXXXXX..    \ O
|| ....XXXXXXXXXXX.
|| ...XXX.......XXX
|| ...XX.........XX
|| ...XX.........XX
|| ...XXX.......XXX
|| ....XXXXXXXXXXX.
|| .....XXXXXXXXX..

|| ...XXXXXXXXXXXXX    \ P
|| ...XXXXXXXXXXXXX
|| ........XX....XX
|| ........XX....XX
|| ........XX....XX
|| ........XX....XX
|| .........XXXXXX.
|| ..........XXXX..

|| .....XXXXXXXXX..    \ Q
|| ....XXXXXXXXXXX.
|| ...XX........XXX
|| ...XX..XX.....XX
|| ...XX.XX......XX
|| ...XXXX......XXX
|| ....XXXXXXXXXXX.
|| ...XX.XXXXXXXX..

|| ...XXXXXXXXXXXXX   \ R
|| ...XXXXXXXXXXXXX
|| .......XXX....XX
|| ......XXXX....XX
|| .....XXXXX....XX
|| ....XXX.XX....XX
|| ...XXX...XXXXXX.
|| ...XX.....XXXX..

|| ....XX....XXXX..    \ S
|| ....XX...XXXXXX.
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XX....XX...XX
|| ...XXX...XX..XX.
|| ...XXXXXXX...XX.
|| .....XXXX.......

|| ..............XX    \ T
|| ..............XX
|| ..............XX
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ..............XX
|| ..............XX
|| ..............XX

|| ......XXXXXXXXXX   \ U
|| ....XXXXXXXXXXXX
|| ...XXX..........
|| ...XX...........
|| ...XX...........
|| ...XXX..........
|| ....XXXXXXXXXXXX
|| ......XXXXXXXXXX

|| .............XXX    \ V
|| .........XXXXXXX
|| ......XXXXXX....
|| ...XXXX.........
|| ...XXXX.........
|| ......XXXXXX....
|| .........XXXXXXX
|| .............XXX

|| ......XXXXXXXXXX    \ W
|| ...XXXXXXXXXXXXX
|| ...XXX..........
|| .....XXXX.......
|| .....XXXX.......
|| ...XXX..........
|| ...XXXXXXXXXXXXX
|| ......XXXXXXXXXX

|| ...XX.........XX    \ X
|| ...XXX.......XXX
|| .....XXX...XXX..
|| .......XXXXX....
|| .......XXXXX....
|| .....XXX...XXX..
|| ...XXX.......XXX
|| ...XX.........XX

|| .............XXX    \ Y
|| ..........XXXXXX
|| ........XXXXX...
|| ...XXXXXXX......
|| ...XXXXXXX......
|| ........XXXXX...
|| ..........XXXXXX
|| .............XXX

|| ...XXX........XX    \ Z
|| ...XXXX.......XX
|| ...XX.XX......XX
|| ...XX..XXX....XX
|| ...XX...XXX...XX
|| ...XX.....XXX.XX
|| ...XX.......XXXX
|| ...XX........XXX

|| ................    \ [
|| ................
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XX............XX
|| XX............XX
|| ................
|| ................

|| ................    \ \
|| ............XXXX
|| ..........XXXX..
|| ........XXXX....
|| ......XXXX......
|| ....XXXX........
|| ...XXX..........
|| ................

|| ................    \ ]
|| ................
|| XX............XX
|| XX............XX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| ................
|| ................

|| ................    \ ^
|| ................
|| .........XXX....
|| ...........XXX..
|| .............XXX
|| ...........XXX..
|| .........XXX....
|| ................

|| XX..............    \ _
|| XX..............
|| XX..............
|| XX..............
|| XX..............
|| XX..............
|| XX..............
|| XX..............

|| ................    \ `
|| ................
|| ...............X
|| ..............XX
|| .............XXX
|| .............XX.
|| ................
|| ................

|| ................    \ a
|| .....XX.........
|| ...XXXXX..XX....
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ...XXXXXXXXXX...
|| ...XXXXXXXX.....

|| ................    \ b
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ....XX....XX....
|| ...XX......XX...
|| ...XX......XX...
|| ....XXXXXXXX....
|| .....XXXXXX.....

|| ................    \ c
|| .....XXXXXX.....
|| ....XXXXXXXX....
|| ...XXX....XXX...
|| ...XX......XX...
|| ...XX......XX...
|| ...XX......XX...
|| ....XX....XX....

|| ................    \ d
|| .....XXXXXX.....
|| ....XXXXXXXX....
|| ...XX......XX...
|| ...XX......XX...
|| ....XX....XX....
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX

|| ................    \ e
|| .....XXXXXXX....
|| ....XXXXXXXXX...
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ...XX..XXXXXX...
|| ....XX.XXXXX....

|| ................    \ f
|| .......XX.......
|| ...XXXXXXXXXXX..
|| ...XXXXXXXXXXXXX
|| .......XX.....XX
|| .......XX.....XX
|| ..............XX
|| .............XX.

|| ..XX............    \ g
|| .XXXX.XX.XXX....
|| XX..XX..XXXXX...
|| X....X.XX...X...
|| X....X.XX...X...
|| XX..XX.XX...XX..
|| .XXXX...XXXXX.X.
|| ..XX.....XXX....

|| ................    \ h
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ..........XX....
|| ...........XX...
|| ...........XX...
|| ...XXXXXXXXXX...
|| ...XXXXXXXXX....

|| ................    \ i
|| ...XX...........
|| ...XX......XX...
|| ...XXXXXXXXXX.XX
|| ...XXXXXXXXXX.XX
|| ...XX...........
|| ...XX...........
|| ................

|| ................    \ j
|| .XX.............
|| XX..............
|| XX..............
|| XX.........XX...
|| XX.........XX...
|| XXXXXXXXXXXXX.XX
|| ..XXXXXXXXXXX.XX

|| ................    \ k
|| ...XXXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| .......XX.......
|| ......XXXX......
|| .....XX..XX.....
|| ....XX....XX....
|| ...XX......XX...

|| ................    \ l
|| ....XXXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ...XX...........
|| ...XX...........
|| ...XX...........
|| ....XX..........
|| ................

|| ................    \ m
|| ...XXXXXXXXXX...
|| ...XXXXXXXXX....
|| ...........XX...
|| ...XXXXXXXXX....
|| ...........XX...
|| ...XXXXXXXXX....
|| ...XXXXXXXX.....

|| ................    \ n
|| ...XXXXXXXXXX...
|| ...XXXXXXXXXX...
|| ..........XX....
|| ...........XX...
|| ...........XX...
|| ...XXXXXXXXX....
|| ...XXXXXXXX.....

|| ................    \ o
|| .....XXXXXX.....
|| ....XXXXXXXX....
|| ...XX......XX...
|| ...XX......XX...
|| ...XX......XX...
|| ....XXXXXXXX....
|| .....XXXXXX.....

|| ................    \ p
|| XXXXXXXXXXXXX...
|| XXXXXXXXXXXXX...
|| ....XX....XX....
|| ...XX......XX...
|| ...XXX.....XX...
|| ....XXXXXXXX....
|| .....XXXXXX.....

|| ................    \ q
|| .....XXXXXX.....
|| ....XXXXXXXX....
|| ...XX......XX...
|| ...XX......XX...
|| ....XX....XX....
|| XXXXXXXXXXXXX...
|| XXXXXXXXXXXXX...

|| ................    \ r
|| ...XXXXXXXXXX...
|| ...XXXXXXXXXX...
|| ..........XX....
|| ...........XX...
|| ...........XX...
|| ...........XX...
|| ..........XX....

|| ................    \ s
|| ....XX...XX.....
|| ...XX...XXXX....
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ...XX..XX..XX...
|| ....XXXX..XX....
|| .....XX.........

|| ................    \ t
|| ...........XX...
|| .....XXXXXXXXXXX
|| ...XXXXXXXXXXXXX
|| ...XX......XX...
|| ...XX......XX...
|| ...XX...........
|| ....XX..........

|| ................    \ u
|| .....XXXXXXXX...
|| ...XXXXXXXXXX...
|| ...XX...........
|| ...XX...........
|| ....XX..........
|| ...XXXXXXXXXX...
|| ...XXXXXXXXXX...

|| ................    \ v
|| ..........XXX...
|| ........XXXXX...
|| .....XXXXX......
|| ...XXXX.........
|| .....XXXXX......
|| ........XXXXX...
|| ..........XXX...

|| ................    \ w
|| ......XXXXXXX...
|| ....XXXXXXXXX...
|| ...XX...........
|| ....XXXXX.......
|| ...XX...........
|| ....XXXXXXXXX...
|| ......XXXXXXX...

|| ................    \ x
|| ...XX......XX...
|| ....XX....XX....
|| .....XXXXXX.....
|| ......XXXX......
|| .....XXXXXX.....
|| ....XX....XX....
|| ...XX......XX...

|| ................    \ y
|| .XX......XXXX...
|| XX.....XXXXXX...
|| XX...XXXX.......
|| .XXX.XX.........
|| ..XXXXXXX.......
|| ....XXXXXXXXX...
|| .........XXXX...

|| ................    \ z
|| ...XXX.....XX...
|| ...XXXX....XX...
|| ...XX.XX...XX...
|| ...XX..XX .XX...
|| ...XX...XX.XX...
|| ...XX....XXXX...
|| ...XX.....XXX...

|| ................    \ {
|| ................
|| .......XXX......
|| ..XXXXXX.XXXXXX.
|| .XXX.........XXX
|| .XX...........XX
|| ................
|| ................

|| ................    \ |
|| ................
|| ................
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| ................
|| ................
|| ................

|| ................    \ }
|| ................
|| .XX...........XX
|| .XXX.........XXX
|| ..XXXXXX.XXXXXX.
|| .......XXX......
|| ................
|| ................

|| ................    \ ~
|| ......XXXX......
|| ......XXXXX.....
|| ........XX......
|| .......XX.......
|| ......XXXXX.....
|| .......XXXX.....
|| ................

|| ................     \ esc = 0x7F
|| ................
|| ................
|| ................
|| ................
|| ................
|| ................
|| ................


|| XXXXXXXXXXXXXXXX    \ Cursor block = 0x80
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX
|| XXXXXXXXXXXXXXXX

|| .......X..X.....    \ € = 0x81
|| .....XXXXXXXX...
|| ...XXXXXXXXXXXX.
|| ..XX...X..X...XX
|| ..XX...X..X...XX
|| ..XX...X..X...XX
|| ...XX.....X..XX.
|| ....XX.......X..

|| ................    \ IJ = 0x82
|| .XX..XXXXXXXX.XX
|| XX...XXXXXXXX.XX
|| XX..............
|| XX..............
|| XX..............
|| XXXXXXXXXXXXX.XX
|| ..XXXXXXXXXXX.XX
align

: BB&EMIT   ( c -- )
    c>n  10 * bigbold +  dup 8 .bitrow \ First half of big char
    x y 1+ xy  1+ 8 .bitrow         \ Second half of big char
    x 0A +  y 1-  xy ;              \ x & y to new char position

: BOLD      ['] bb&emit to o-emit ;


\ Example
: BOLDDEMO  ( -- )                  \ Display thin large token set
    display-setup  bold  &page
    04 0 xy" Egel project"          \ Startup message
    0E 2 xy" Characters"            \ To line 2
    14 4 xy" by J.J.H."             \ To line 4
    key drop  &page
    4 0 do
        0 i 2* xy
        i 0D * bl +  0D 0 do  dup &emit  1+  loop  drop
    loop
    key drop  &page
    2 0 do
        0 i 4 * xy 
        6 0 do  bl &emit  82 &emit  loop
        0 i 4 * 2 + xy 
        6 0 do  81 &emit  bl &emit  loop
    loop ;

\ End ;;;
